# Generated by Django 5.2.10 on 2026-05-14 07:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_devicerequest_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('pc', 'PC'), ('laptop', 'Laptop'), ('headphone', 'Headphone'), ('connector', 'Connector'), ('mobile', 'Mobile')], db_index=True, max_length=20)),
                ('asset_name', models.CharField(db_index=True, max_length=255)),
                ('serial_number', models.CharField(db_index=True, help_text='Unique identifier from CSV', max_length=100, unique=True)),
                ('assigned_person_name', models.CharField(db_index=True, max_length=255)),
                ('assigned_email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('assigned_date', models.DateField(blank=True, null=True)),
                ('assigned_by', models.CharField(blank=True, max_length=255)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('pending_claim', 'Pending Claim'), ('claimed', 'Claimed'), ('retired', 'Retired')], db_index=True, default='pending_claim', max_length=20)),
                ('condition', models.CharField(choices=[('new', 'New'), ('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=20)),
                ('claimed', models.BooleanField(db_index=True, default=False)),
                ('pending_claim', models.BooleanField(db_index=True, default=True)),
                ('mail_sent', models.BooleanField(default=False)),
                ('mail_sent_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Stores category-specific fields as JSON')),
                ('csv_import_id', models.CharField(blank=True, help_text='CSV import batch identifier', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventory Asset',
                'verbose_name_plural': 'Inventory Assets',
                'db_table': 'inventory_assets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'status'], name='inventory_a_categor_00e910_idx'), models.Index(fields=['assigned_email', 'claimed'], name='inventory_a_assigne_dcfbb9_idx'), models.Index(fields=['serial_number'], name='inventory_a_serial__e22f1e_idx')],
            },
        ),
    ]
