# Generated by Django 5.2.10 on 2026-04-06 09:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_load_initial_devices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='consent_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='consent_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='consent_approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignment',
            name='consent_form_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='assignment',
            name='consent_images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='assignment',
            name='return_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='return_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='return_approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignment',
            name='return_form_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='assignment',
            name='return_images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('consent_pending', 'Consent Pending'), ('active', 'Active'), ('returned', 'Returned'), ('lost', 'Lost'), ('damaged', 'Damaged')], default='pending_approval', max_length=20),
        ),
        migrations.CreateModel(
            name='DeviceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_type', models.CharField(choices=[('laptop', 'Laptop'), ('desktop', 'Desktop'), ('monitor', 'Monitor'), ('keyboard', 'Keyboard'), ('mouse', 'Mouse'), ('headset', 'Headset'), ('phone', 'Phone'), ('tablet', 'Tablet'), ('other', 'Other')], max_length=20)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('specifications', models.JSONField(default=dict)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('assigned', 'Assigned')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device Request',
                'verbose_name_plural': 'Device Requests',
                'db_table': 'device_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
