# Generated by Django 5.2.10 on 2026-04-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_assignment_consent_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='image_url',
            field=models.URLField(blank=True, help_text='Live link to device image'),
        ),
    ]
