# Generated by Django 5.2.10 on 2026-05-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_assignment_cycle_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='return_request_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='return_request_reason',
            field=models.TextField(blank=True, help_text="User's reason for return request"),
        ),
        migrations.AddField(
            model_name='assignment',
            name='return_request_rejection_reason',
            field=models.TextField(blank=True, help_text="Admin's reason for rejecting return"),
        ),
        migrations.AddField(
            model_name='assignment',
            name='return_request_remarks',
            field=models.TextField(blank=True, help_text="User's remarks about device condition"),
        ),
        migrations.AddField(
            model_name='assignment',
            name='return_request_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
