# Generated by Django 5.2.10 on 2026-04-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_add_device_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('laptop', 'Laptop'), ('desktop', 'Desktop'), ('pc', 'PC'), ('monitor', 'Monitor'), ('keyboard', 'Keyboard'), ('mouse', 'Mouse'), ('headset', 'Headset'), ('headphone', 'Headphone'), ('phone', 'Phone'), ('tablet', 'Tablet'), ('cable', 'Cable'), ('charger', 'Charger'), ('pendrive', 'Pendrive'), ('hard_drive', 'Hard Drive'), ('accessories', 'Accessories'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='devicerequest',
            name='device_type',
            field=models.CharField(choices=[('laptop', 'Laptop'), ('desktop', 'Desktop'), ('pc', 'PC'), ('monitor', 'Monitor'), ('keyboard', 'Keyboard'), ('mouse', 'Mouse'), ('headset', 'Headset'), ('headphone', 'Headphone'), ('phone', 'Phone'), ('tablet', 'Tablet'), ('cable', 'Cable'), ('charger', 'Charger'), ('pendrive', 'Pendrive'), ('hard_drive', 'Hard Drive'), ('accessories', 'Accessories'), ('other', 'Other')], max_length=20),
        ),
    ]
