# Generated by Codex on 2026-04-23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_alter_device_device_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicerequest",
            name="assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_device_requests",
                to="inventory.assignment",
            ),
        ),
    ]
