# Generated by Django 5.2.10 on 2026-04-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hrms_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
