# Generated by Codex on 2026-04-23

from django.db import migrations, models
from django.utils.text import slugify


def build_base_username(employee):
    name_parts = [
        (getattr(employee, "first_name", "") or "").strip(),
        (getattr(employee, "last_name", "") or "").strip(),
    ]
    full_name = " ".join(part for part in name_parts if part)
    if full_name:
        return slugify(full_name).replace("-", ".")

    email = (getattr(employee, "email", "") or "").strip().lower()
    if email:
        return email.split("@", 1)[0]

    employee_id = (getattr(employee, "employee_id", "") or "").strip().lower()
    if employee_id:
        return employee_id

    return "user"


def populate_usernames(apps, schema_editor):
    Employee = apps.get_model("authentication", "Employee")

    for employee in Employee.objects.all().order_by("date_joined", "email"):
        base_username = (build_base_username(employee).strip(".") or "user")[:140]
        candidate = base_username
        suffix = 1

        while Employee.objects.exclude(pk=employee.pk).filter(username__iexact=candidate).exists():
            suffix_text = str(suffix)
            candidate = f"{base_username[:150 - len(suffix_text)]}{suffix_text}"
            suffix += 1

        employee.username = candidate.lower()
        employee.save(update_fields=["username"])


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_employee_email_verified_employee_email_verified_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="username",
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, unique=True),
        ),
        migrations.RunPython(populate_usernames, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="employee",
            name="username",
            field=models.CharField(db_index=True, max_length=150, unique=True),
        ),
    ]
